package ca.sheridancollege.alagao.controllers;

import ca.sheridancollege.alagao.beans.User;
import ca.sheridancollege.alagao.database.DatabaseAccess;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/v1/users")
public class UserRestController {

    @Autowired
    private DatabaseAccess databaseAccess;

    @GetMapping
    public List<User> getAllUsers() {
        return databaseAccess.findAllUsers();
    }

    @GetMapping("/{id}")
    public User getUserById(@PathVariable Long id) {
        return databaseAccess.findUserAccount(id);
    }

    @PostMapping(consumes = "application/json")
    public User createUser(@RequestBody User user) {
        databaseAccess.createUser(user);
        return user; // Ideally, return the user with an ID if it's generated by the database
    }

    @PutMapping("/{id}")
    public User updateUser(@PathVariable Long id, @RequestBody User user) {
        user.setUserID(id);
        databaseAccess.updateUser(user);
        return user;
    }

    @DeleteMapping("/{id}")
    public String deleteUser(@PathVariable Long id) {
        databaseAccess.deleteUser(id);
        return "User with ID: " + id + " deleted successfully";
    }

    // Additional methods as needed
}
